[package]
name = "vulkan-project"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
image = "0.25.2"
log = "0.4.22"
pretty_env_logger = "0.5.0"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = "0.30.5"
